name: Android Lint Check

on: pull_request

permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    name: lint-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Set up JDK
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: ktlint
        uses: ScaCap/action-ktlint@v1.7.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: file
          fail_on_error: true
          android: true
